In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
import matplotlib as plt

In [ ]:
!pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
%matplotlib inline

In [ ]:
import tensorflow as tf

In [ ]:
print (f'tensorflow ver: {tf.__version__}')

tensorflow ver: 2.9.2


In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

In [ ]:
from sklearn.compose import ColumnTransformer

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
dataset = pd.read_csv('AnnFolder/DataSet_for_ANN.csv')

In [ ]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
print (f'no of rows = {dataset.shape[0]}')

no of rows = 10000


In [ ]:
X = dataset.iloc[:, 3:-1].values

In [ ]:
Y = dataset.iloc[:, -1].values

In [ ]:
le = LabelEncoder()

In [ ]:
X[:, 2] = le.fit_transform(X[:, 2])

In [ ]:
ct = ColumnTransformer(
    transformers=[(
        'encoder',
        OneHotEncoder(),
        [1])
    ],
    remainder='passthrough'
)

In [ ]:
X = np.array(ct.fit_transform(X))

In [ ]:
X.shape

(10000, 12)

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=0
)

In [ ]:
sc  = StandardScaler()

In [ ]:
X_train = sc.fit_transform(X_train)

In [ ]:
X_test = sc.transform(X_test)

In [ ]:
ann = tf.keras.models.Sequential()

In [ ]:
ann

In [ ]:
ann.add(
    tf.keras.layers.Dense(
        units=6,
        activation='relu'
    )
)

In [ ]:
ann.add(
    tf.keras.layers.Dense(
        units=6,
        activation='relu'
    )
)

In [ ]:
ann.add(
    tf.keras.layers.Dense(
        units=1,
        activation='sigmoid'
    )
)

In [ ]:
ann.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [ ]:
results = ann.fit(X_train, Y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5626 - accuracy: 0.7530
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4615 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4395 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4303 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4254 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4206 - accuracy: 0.7962
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4134 - accuracy: 0.8012
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4013 - accuracy: 0.8102
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3884 - accuracy: 0.8156
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3770 - accura

In [ ]:
ann.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (32, 6)                   78        
                                                                 
 dense_1 (Dense)             (32, 6)                   42        
                                                                 
 dense_2 (Dense)             (32, 1)                   7         
                                                                 
Total params: 127
Trainable params: 127
Non-trainable params: 0
_________________________________________________________________


In [ ]:
len(Y_test)

2000

In [ ]:
y_p = ann.predict(X_test)

63/63 [==============================] - 0s 2ms/step


In [ ]:
y_p.shape

(2000, 1)

In [ ]:
y_p = (y_p > 0.5)

In [ ]:
y_p

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [ ]:
print(
    np.concatenate(
        (y_p.reshape(len(y_p), 1), Y_test.reshape(len(Y_test), 1)),
        1
    )
)

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
Y_pred = ann.predict(X_test)

63/63 [==============================] - 0s 2ms/step


In [ ]:
Y_test

array([0, 1, 0, ..., 0, 0, 0])

In [ ]:
Y_pred

array([[0.26990974],
       [0.3552275 ],
       [0.15047662],
       ...,
       [0.26810068],
       [0.1515278 ],
       [0.21770631]], dtype=float32)

In [ ]:
Y_pred = (ann.predict(X_test) > 0.5)

63/63 [==============================] - 0s 2ms/step


In [ ]:
Y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [ ]:
print (
    np.concatenate(
        (Y_pred.reshape(len(Y_pred), 1), Y_test.reshape(len(Y_test), 1)),
        1
    )
)

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
cm = confusion_matrix(Y_test, y_p)

In [ ]:
print(cm)

[[1516   79]
 [ 191  214]]


In [ ]:
accuracy_score(Y_test, y_p)

0.865

In [ ]:
print (ann.predict(sc.transform([[0, 1, 0, 376, 0, 29, 4, 115046, 4, 1, 0, 11346]])) > 0.5)

1/1 [==============================] - 0s 37ms/step
[[ True]]
